# Generated by Django 5.2.11 on 2026-05-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherinfo",
            name="email",
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="friends",
            field=models.ManyToManyField(blank=True, to="users.teacherinfo"),
        ),
    ]
