# Generated by Django 5.2.11 on 2026-05-12 13:24

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_teacherinfo_email_teacherinfo_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherinfo",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[users.validators.validate_image_file],
            ),
        ),
    ]
