# Generated by Django 5.2.13 on 2026-05-05 11:26

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("patronymic", models.CharField(max_length=100, null=True)),
                (
                    "email",
                    models.TextField(
                        default="no email",
                        unique=True,
                        validators=[catalog.validators.real_email],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[catalog.validators.real_number],
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, validators=[catalog.validators.real_age]
                    ),
                ),
            ],
        ),
    ]
