# Generated by Django 5.2.11 on 2026-03-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_course_teacher_alter_course_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="patronymic",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="patronymic",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="email",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="phone",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
