# Generated by Django 5.2.11 on 2026-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_course_date_student_birthday_student_patronymic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="birthday",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="email",
            field=models.TextField(unique=True),
        ),
    ]
