# Generated by Django 5.2.11 on 2026-04-07 08:32

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_course_title_alter_student_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.TextField(
                default="no email",
                unique=True,
                validators=[catalog.validators.real_email],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, validators=[catalog.validators.real_age]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                max_length=30, unique=True, validators=[catalog.validators.real_number]
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="patronymic",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, validators=[catalog.validators.real_age]
            ),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="email",
            field=models.TextField(
                blank=True, unique=True, validators=[catalog.validators.real_email]
            ),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="phone",
            field=models.CharField(
                max_length=30, unique=True, validators=[catalog.validators.real_number]
            ),
        ),
    ]
