# Generated by Django 5.2.11 on 2026-04-13 14:51

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_student_email_alter_course_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherinfo",
            name="birthday",
            field=models.DateField(validators=[catalog.validators.real_age]),
        ),
    ]
